version: 1.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  project: AutoReservation.sln
  verbosity: detailed
environment:
  COVERALLS_REPO_TOKEN:
    secure: +7h2hB/WnQCeWmtuHXc3m2R3gaU8tUPqgC92VJB2AJH/OUdTg1Ddd0L7ax3FvL1j
after_test:
  - cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:AutoReservation.BusinessLayer.Testing/bin/debug/AutoReservation.BusinessLayer.Testing.dll" -output:coverage.xml
  - cmd: packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml